development:
 adapter: postgresql
 encoding: unicode
 host: localhost
 username: postgres
 password: secure
 database: diction_development
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 host: localhost
 username: postgres
 password: secure
 database: diction_test
 pool: 5
